'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="KB")>  _
Partial Public Class DataClasses3DataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definiciones de métodos de extensibilidad"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.AccesoDatos.My.MySettings.Default.KBConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_cliente")>  _
	Public Function Trae_cliente() As ISingleResult(Of Trae_clienteResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_clienteResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_detalleStok")>  _
	Public Function Trae_detalleStok() As ISingleResult(Of Trae_detalleStokResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_detalleStokResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_detalleVentas")>  _
	Public Function Trae_detalleVentas() As ISingleResult(Of Trae_detalleVentasResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_detalleVentasResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_empleados")>  _
	Public Function Trae_empleados() As ISingleResult(Of Trae_empleadosResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_empleadosResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_perfiles")>  _
	Public Function Trae_perfiles() As ISingleResult(Of Trae_perfilesResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_perfilesResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_producto")>  _
	Public Function Trae_producto() As ISingleResult(Of Trae_productoResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_productoResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_provedores")>  _
	Public Function Trae_provedores() As ISingleResult(Of Trae_provedoresResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_provedoresResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_stok")>  _
	Public Function Trae_stok() As ISingleResult(Of Trae_stokResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_stokResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_usuarios")>  _
	Public Function Trae_usuarios() As ISingleResult(Of Trae_usuariosResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_usuariosResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Trae_ventas")>  _
	Public Function Trae_ventas() As ISingleResult(Of Trae_ventasResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo))
		Return CType(result.ReturnValue,ISingleResult(Of Trae_ventasResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Elimina_producto")>  _
	Public Function Elimina_producto(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal id As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="NVarChar(MAX)")> ByVal nombre As String) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), id, nombre)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Inserta_actualizaProducto")>  _
	Public Function Inserta_actualizaProducto(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal id_Prod As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Id_prov", DbType:="Int")> ByVal id_prov As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Nombre", DbType:="NVarChar(MAX)")> ByVal nombre As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Precio_c", DbType:="Decimal(18,2)")> ByVal precio_c As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Precio_V", DbType:="Decimal(18,2)")> ByVal precio_V As System.Nullable(Of Decimal), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Imagen", DbType:="Image")> ByVal imagen As System.Data.Linq.Binary, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Fecha", DbType:="DateTime")> ByVal fecha As System.Nullable(Of Date)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), id_Prod, id_prov, nombre, precio_c, precio_V, imagen, fecha)
		Return CType(result.ReturnValue,Integer)
	End Function
End Class

Partial Public Class Trae_clienteResult
	
	Private _id_Cliente As Integer
	
	Private _Nombre As String
	
	Private _Apellido_P As String
	
	Private _Apellido_M As String
	
	Private _RFC As System.Nullable(Of Integer)
	
	Private _Correo As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_Cliente", DbType:="Int NOT NULL")>  _
	Public Property id_Cliente() As Integer
		Get
			Return Me._id_Cliente
		End Get
		Set
			If ((Me._id_Cliente = value)  _
						= false) Then
				Me._id_Cliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Nombre", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property Nombre() As String
		Get
			Return Me._Nombre
		End Get
		Set
			If (String.Equals(Me._Nombre, value) = false) Then
				Me._Nombre = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Apellido_P", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property Apellido_P() As String
		Get
			Return Me._Apellido_P
		End Get
		Set
			If (String.Equals(Me._Apellido_P, value) = false) Then
				Me._Apellido_P = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Apellido_M", DbType:="VarChar(40) NOT NULL", CanBeNull:=false)>  _
	Public Property Apellido_M() As String
		Get
			Return Me._Apellido_M
		End Get
		Set
			If (String.Equals(Me._Apellido_M, value) = false) Then
				Me._Apellido_M = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RFC", DbType:="Int")>  _
	Public Property RFC() As System.Nullable(Of Integer)
		Get
			Return Me._RFC
		End Get
		Set
			If (Me._RFC.Equals(value) = false) Then
				Me._RFC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Correo", DbType:="NVarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Correo() As String
		Get
			Return Me._Correo
		End Get
		Set
			If (String.Equals(Me._Correo, value) = false) Then
				Me._Correo = value
			End If
		End Set
	End Property
End Class

Partial Public Class Trae_detalleStokResult
	
	Private _Id_DS As Integer
	
	Private _Id_Prod As Integer
	
	Private _Salidas As Integer
	
	Private _Entradas As Integer
	
	Private _Cantidad As Integer
	
	Private _Total As Integer
	
	Private _Fecha As Date
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_DS", DbType:="Int NOT NULL")>  _
	Public Property Id_DS() As Integer
		Get
			Return Me._Id_DS
		End Get
		Set
			If ((Me._Id_DS = value)  _
						= false) Then
				Me._Id_DS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Prod", DbType:="Int NOT NULL")>  _
	Public Property Id_Prod() As Integer
		Get
			Return Me._Id_Prod
		End Get
		Set
			If ((Me._Id_Prod = value)  _
						= false) Then
				Me._Id_Prod = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Salidas", DbType:="Int NOT NULL")>  _
	Public Property Salidas() As Integer
		Get
			Return Me._Salidas
		End Get
		Set
			If ((Me._Salidas = value)  _
						= false) Then
				Me._Salidas = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Entradas", DbType:="Int NOT NULL")>  _
	Public Property Entradas() As Integer
		Get
			Return Me._Entradas
		End Get
		Set
			If ((Me._Entradas = value)  _
						= false) Then
				Me._Entradas = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cantidad", DbType:="Int NOT NULL")>  _
	Public Property Cantidad() As Integer
		Get
			Return Me._Cantidad
		End Get
		Set
			If ((Me._Cantidad = value)  _
						= false) Then
				Me._Cantidad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Total", DbType:="Int NOT NULL")>  _
	Public Property Total() As Integer
		Get
			Return Me._Total
		End Get
		Set
			If ((Me._Total = value)  _
						= false) Then
				Me._Total = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fecha", DbType:="DateTime NOT NULL")>  _
	Public Property Fecha() As Date
		Get
			Return Me._Fecha
		End Get
		Set
			If ((Me._Fecha = value)  _
						= false) Then
				Me._Fecha = value
			End If
		End Set
	End Property
End Class

Partial Public Class Trae_detalleVentasResult
	
	Private _Factura As Integer
	
	Private _Id_Prod As Integer
	
	Private _Cantidad As Integer
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Factura", DbType:="Int NOT NULL")>  _
	Public Property Factura() As Integer
		Get
			Return Me._Factura
		End Get
		Set
			If ((Me._Factura = value)  _
						= false) Then
				Me._Factura = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Prod", DbType:="Int NOT NULL")>  _
	Public Property Id_Prod() As Integer
		Get
			Return Me._Id_Prod
		End Get
		Set
			If ((Me._Id_Prod = value)  _
						= false) Then
				Me._Id_Prod = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cantidad", DbType:="Int NOT NULL")>  _
	Public Property Cantidad() As Integer
		Get
			Return Me._Cantidad
		End Get
		Set
			If ((Me._Cantidad = value)  _
						= false) Then
				Me._Cantidad = value
			End If
		End Set
	End Property
End Class

Partial Public Class Trae_empleadosResult
	
	Private _Id_E As Integer
	
	Private _Id_Us As Integer
	
	Private _Id_P As Integer
	
	Private _Nombre As String
	
	Private _Apellido_P As String
	
	Private _Apellido_M As String
	
	Private _Correo As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_E", DbType:="Int NOT NULL")>  _
	Public Property Id_E() As Integer
		Get
			Return Me._Id_E
		End Get
		Set
			If ((Me._Id_E = value)  _
						= false) Then
				Me._Id_E = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Us", DbType:="Int NOT NULL")>  _
	Public Property Id_Us() As Integer
		Get
			Return Me._Id_Us
		End Get
		Set
			If ((Me._Id_Us = value)  _
						= false) Then
				Me._Id_Us = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_P", DbType:="Int NOT NULL")>  _
	Public Property Id_P() As Integer
		Get
			Return Me._Id_P
		End Get
		Set
			If ((Me._Id_P = value)  _
						= false) Then
				Me._Id_P = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Nombre", DbType:="VarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Nombre() As String
		Get
			Return Me._Nombre
		End Get
		Set
			If (String.Equals(Me._Nombre, value) = false) Then
				Me._Nombre = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Apellido_P", DbType:="VarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Apellido_P() As String
		Get
			Return Me._Apellido_P
		End Get
		Set
			If (String.Equals(Me._Apellido_P, value) = false) Then
				Me._Apellido_P = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Apellido_M", DbType:="VarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Apellido_M() As String
		Get
			Return Me._Apellido_M
		End Get
		Set
			If (String.Equals(Me._Apellido_M, value) = false) Then
				Me._Apellido_M = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Correo", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Correo() As String
		Get
			Return Me._Correo
		End Get
		Set
			If (String.Equals(Me._Correo, value) = false) Then
				Me._Correo = value
			End If
		End Set
	End Property
End Class

Partial Public Class Trae_perfilesResult
	
	Private _Id_P As Integer
	
	Private _Puesto As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_P", DbType:="Int NOT NULL")>  _
	Public Property Id_P() As Integer
		Get
			Return Me._Id_P
		End Get
		Set
			If ((Me._Id_P = value)  _
						= false) Then
				Me._Id_P = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Puesto", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Puesto() As String
		Get
			Return Me._Puesto
		End Get
		Set
			If (String.Equals(Me._Puesto, value) = false) Then
				Me._Puesto = value
			End If
		End Set
	End Property
End Class

Partial Public Class Trae_productoResult
	
	Private _Id_Prod As Integer
	
	Private _Id_Prov As Integer
	
	Private _Nombre As String
	
	Private _Precio_C As Decimal
	
	Private _Precio_V As Decimal
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Prod", DbType:="Int NOT NULL")>  _
	Public Property Id_Prod() As Integer
		Get
			Return Me._Id_Prod
		End Get
		Set
			If ((Me._Id_Prod = value)  _
						= false) Then
				Me._Id_Prod = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Prov", DbType:="Int NOT NULL")>  _
	Public Property Id_Prov() As Integer
		Get
			Return Me._Id_Prov
		End Get
		Set
			If ((Me._Id_Prov = value)  _
						= false) Then
				Me._Id_Prov = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Nombre", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Nombre() As String
		Get
			Return Me._Nombre
		End Get
		Set
			If (String.Equals(Me._Nombre, value) = false) Then
				Me._Nombre = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Precio_C", DbType:="Decimal(5,2) NOT NULL")>  _
	Public Property Precio_C() As Decimal
		Get
			Return Me._Precio_C
		End Get
		Set
			If ((Me._Precio_C = value)  _
						= false) Then
				Me._Precio_C = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Precio_V", DbType:="Decimal(5,2) NOT NULL")>  _
	Public Property Precio_V() As Decimal
		Get
			Return Me._Precio_V
		End Get
		Set
			If ((Me._Precio_V = value)  _
						= false) Then
				Me._Precio_V = value
			End If
		End Set
	End Property
End Class

Partial Public Class Trae_provedoresResult
	
	Private _Id_Prov As Integer
	
	Private _Nombre As String
	
	Private _Correo As String
	
	Private _Numero As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Prov", DbType:="Int NOT NULL")>  _
	Public Property Id_Prov() As Integer
		Get
			Return Me._Id_Prov
		End Get
		Set
			If ((Me._Id_Prov = value)  _
						= false) Then
				Me._Id_Prov = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Nombre", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Nombre() As String
		Get
			Return Me._Nombre
		End Get
		Set
			If (String.Equals(Me._Nombre, value) = false) Then
				Me._Nombre = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Correo", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Correo() As String
		Get
			Return Me._Correo
		End Get
		Set
			If (String.Equals(Me._Correo, value) = false) Then
				Me._Correo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Numero", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Numero() As String
		Get
			Return Me._Numero
		End Get
		Set
			If (String.Equals(Me._Numero, value) = false) Then
				Me._Numero = value
			End If
		End Set
	End Property
End Class

Partial Public Class Trae_stokResult
	
	Private _Id_Stock As Integer
	
	Private _Id_Prod As Integer
	
	Private _Cantidad As Integer
	
	Private _Fecha_Ingreso As Date
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Stock", DbType:="Int NOT NULL")>  _
	Public Property Id_Stock() As Integer
		Get
			Return Me._Id_Stock
		End Get
		Set
			If ((Me._Id_Stock = value)  _
						= false) Then
				Me._Id_Stock = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Prod", DbType:="Int NOT NULL")>  _
	Public Property Id_Prod() As Integer
		Get
			Return Me._Id_Prod
		End Get
		Set
			If ((Me._Id_Prod = value)  _
						= false) Then
				Me._Id_Prod = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cantidad", DbType:="Int NOT NULL")>  _
	Public Property Cantidad() As Integer
		Get
			Return Me._Cantidad
		End Get
		Set
			If ((Me._Cantidad = value)  _
						= false) Then
				Me._Cantidad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fecha_Ingreso", DbType:="DateTime NOT NULL")>  _
	Public Property Fecha_Ingreso() As Date
		Get
			Return Me._Fecha_Ingreso
		End Get
		Set
			If ((Me._Fecha_Ingreso = value)  _
						= false) Then
				Me._Fecha_Ingreso = value
			End If
		End Set
	End Property
End Class

Partial Public Class Trae_usuariosResult
	
	Private _Id_Us As Integer
	
	Private __User As String
	
	Private __Password As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Us", DbType:="Int NOT NULL")>  _
	Public Property Id_Us() As Integer
		Get
			Return Me._Id_Us
		End Get
		Set
			If ((Me._Id_Us = value)  _
						= false) Then
				Me._Id_Us = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[_User]", Storage:="__User", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property _User() As String
		Get
			Return Me.__User
		End Get
		Set
			If (String.Equals(Me.__User, value) = false) Then
				Me.__User = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[_Password]", Storage:="__Password", DbType:="NVarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property _Password() As String
		Get
			Return Me.__Password
		End Get
		Set
			If (String.Equals(Me.__Password, value) = false) Then
				Me.__Password = value
			End If
		End Set
	End Property
End Class

Partial Public Class Trae_ventasResult
	
	Private _Clave As Integer
	
	Private _Id_Factura As Integer
	
	Private _Id_Empleado As Integer
	
	Private _Id_Cliente As Integer
	
	Private _Sub_t As Integer
	
	Private _IVA As Integer
	
	Private _Total As Integer
	
	Private _Fecha As Date
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Clave", DbType:="Int NOT NULL")>  _
	Public Property Clave() As Integer
		Get
			Return Me._Clave
		End Get
		Set
			If ((Me._Clave = value)  _
						= false) Then
				Me._Clave = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Factura", DbType:="Int NOT NULL")>  _
	Public Property Id_Factura() As Integer
		Get
			Return Me._Id_Factura
		End Get
		Set
			If ((Me._Id_Factura = value)  _
						= false) Then
				Me._Id_Factura = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Empleado", DbType:="Int NOT NULL")>  _
	Public Property Id_Empleado() As Integer
		Get
			Return Me._Id_Empleado
		End Get
		Set
			If ((Me._Id_Empleado = value)  _
						= false) Then
				Me._Id_Empleado = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Id_Cliente", DbType:="Int NOT NULL")>  _
	Public Property Id_Cliente() As Integer
		Get
			Return Me._Id_Cliente
		End Get
		Set
			If ((Me._Id_Cliente = value)  _
						= false) Then
				Me._Id_Cliente = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Sub_t", DbType:="Int NOT NULL")>  _
	Public Property Sub_t() As Integer
		Get
			Return Me._Sub_t
		End Get
		Set
			If ((Me._Sub_t = value)  _
						= false) Then
				Me._Sub_t = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IVA", DbType:="Int NOT NULL")>  _
	Public Property IVA() As Integer
		Get
			Return Me._IVA
		End Get
		Set
			If ((Me._IVA = value)  _
						= false) Then
				Me._IVA = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Total", DbType:="Int NOT NULL")>  _
	Public Property Total() As Integer
		Get
			Return Me._Total
		End Get
		Set
			If ((Me._Total = value)  _
						= false) Then
				Me._Total = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fecha", DbType:="DateTime NOT NULL")>  _
	Public Property Fecha() As Date
		Get
			Return Me._Fecha
		End Get
		Set
			If ((Me._Fecha = value)  _
						= false) Then
				Me._Fecha = value
			End If
		End Set
	End Property
End Class
